#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

mkdir_p 'tmp/dpl-test/snap'
mkdir_p 'tmp/dpl-test/src'
chdir 'tmp/dpl-test'

File.write 'src/dpl-test', <<~str
  #!/bin/bash
  echo "hello, friend!"
str

FileUtils.chmod 0755, "src/dpl-test"

File.write 'snap/snapcraft.yaml', <<~str
  name: dpl-test
  version: "0.0.0-test.#{ENV['ID'][0..5]}"
  summary: Travis CI dpl canary test snap
  description: Travis CI dpl canary test snap.
  base: core18
  confinement: strict
  grade: stable

  apps:
    dpl-test:
      command: dpl-test

  parts:
    dpl-test:
      plugin: dump
      source: src
str

cmd = 'snapcraft snap'
puts cmd
system cmd
